# Site settings
title: Phoenix JavaScript
email: brad@azpixels.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phoenixjavascript.org" # the base hostname & protocol for your site
twitter_username: phxjavascript

# Build settings
markdown: kramdown
